feat: add monthly activity share feature
api7/contributor-graph pull request #55
Opened 2021-06-14 02:37 UTC by LiteSun

This PR aims to add monthly activity share feature.

![image](https://user-images.githubusercontent.com/31329157/121832326-613acb00-ccfc-11eb-9b4e-7b3d6508f3ed.png)
![image](https://user-images.githubusercontent.com/31329157/121832348-6b5cc980-ccfc-11eb-8e2b-b093205bae49.png)

2021-06-14 02:46 UTC, Yiyiyimu approved these changes

2021-06-14 03:57 UTC, moonming requested changes
wrong desc about twitter share

2021-06-15 00:52 UTC, LiteSun commented
> wrong desc about twitter share

Good catch. will fix it soon.

2021-06-15 12:09 UTC, moonming approved these changes

2021-06-15 14:44 UTC, merged